src/iluminare/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'iluminare.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # a primeira pagina do site e a primeira pagina no madulo 'entrada'
    (r'^$', 'iluminare.limbo.views.index'),
    #(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.ILUMINARE_ROOT + "static"}),

    # o app entrada tera as urls administradas em entrada/urls.py
    (r'^paciente/', include('iluminare.paciente.urls')),
    (r'^voluntario/', include('iluminare.voluntario.urls')),
    (r'^limbo/', include('iluminare.limbo.urls')),
    (r'^util/', include('iluminare.util.urls')),
    (r'^relatorio/', include('iluminare.relatorio.urls')),
    (r'^atendimento/', include('iluminare.atendimento.urls')),
    (r'^tratamento/', include('iluminare.tratamento.urls')),
)

src/iluminare/tratamento/models.py
# coding: utf-8
from django.db import models
from iluminare.paciente.models import Paciente

class Sala(models.Model):
    descricao   = models.CharField(max_length = 45, blank = False, null = False)

    def __unicode__(self):
        return "%s" % self.descricao 

class Tratamento(models.Model):
    DIAS = ( 
        ('D', 'Domingo'),
        ('S', 'Segunda'),
        ('T', 'Terça'),
        ('Q', 'Quarta'),
        ('N', 'Quinta'),
        ('X', 'Sexta'),
        ('B', 'Sábado'))
    
    sala                = models.ForeignKey(Sala, null = True, blank = True)
    descricao_basica    = models.CharField(max_length=100, blank = False, null = False)
    descricao_completa  = models.TextField(blank = True, null = True)
    dia_semana          = models.CharField(max_length=1, choices = DIAS, null = True, blank = True)	
    horario_limite      = models.TimeField(null = True, blank = True)
    max_agendamentos    = models.IntegerField(null = True, blank = True)

    def __unicode__(self):
        return "%s" % (self.descricao_basica)

class TratamentoPaciente(models.Model):
    # talvez seja necessário ajustar esses status mais pra frente.
    STATUS = ( 
        ('C', 'Concluído'),
        ('A', 'Em Andamento'),
        ('E', 'Encaminhado'), # O paciente foi encaminhado, mas ainda não iniciou o tratamento.
        ('D', 'Desistiu'),
        ('T', 'Temporariamente afastado'))
        
    paciente    = models.ForeignKey(Paciente, null = False, blank = False)
    tratamento  = models.ForeignKey(Tratamento, null = False, blank = False)

    data_inicio = models.DateField(null=True, blank=True)
    data_fim    = models.DateField(null=True, blank=True)

    status      = models.CharField(max_length=1, choices = STATUS, null = True, blank = True)	
    def __unicode__(self):
        return "%s %s (%s - %s)" % (self.paciente.nome, self.tratamento, self.data_inicio, self.data_fim)

class InstanciaTratamento(models.Model):
    tratamento          = models.ForeignKey(Tratamento, null = False, blank = False)
    
    data                = models.DateField(null = False, blank = False)    
    medico_espiritual   = models.CharField(max_length = 45, blank = True, null = True)
    coletivo            = models.BooleanField(blank = True, default=False)
    observacoes         = models.TextField(blank = True, null = True)

    def __unicode__(self):
        return u'%s em %s' % (self.tratamento, self.data)
		
class AgendaTratamento(models.Model):
    tratamento          = models.ForeignKey(Tratamento, null = False, blank = False)
    # A data nula indica uma agenda de tratamento genérica
    data                = models.DateField(null = True, blank = True)
    max_agendamentos    = models.SmallIntegerField(null = True, blank = True)
    
    def __unicode__(self):
        data_str = str(self.data)
        if self.data == None:
            data_str = 'Sem data'
        return u'%s / %s' % (self.tratamento, data_str)

src/iluminare/voluntario/models.py
# coding: utf-8

from django.db import models
from iluminare.paciente.models import Paciente
from iluminare.tratamento.models import Tratamento

class Funcao(models.Model):
    descricao       = models.TextField(null = False, blank = False)
    tratamento      = models.ForeignKey(Tratamento, null = True, blank = True)

    def __unicode__(self):
        return self.descricao

class Voluntario(models.Model):
    # Retiramos a opcao (C, Colaborador).
    # A partir de 2014 o perfil colaborador deixou de existir.
    # A base de dados e algumas telas do sistema continuam com o colaborador para consulta.
    TIPO = (('T', "Trabalhador"),('A',"Apoio"))
    DIAS = (
        ('T', 'Terça'),
        ('X', 'Sexta'))

    paciente        = models.ForeignKey(Paciente, null = False, blank = False)
    tipo            = models.CharField(max_length = 1, choices = TIPO)
    data_inicio     = models.DateField(null = True, blank = True)
    data_fim        = models.DateField(null = True, blank = True)
    ativo           = models.BooleanField(blank = True, default=True)
    observacao      = models.TextField(null = True, blank = True)
    dia_estudo      = models.CharField(max_length=1, choices = DIAS, null = True, blank = True)

    class Meta:
        ordering = ['paciente__nome']


    def __unicode__(self):
        return "%s status: %s" % (self.paciente.nome, self.tipo)

class Trabalho(models.Model):
    STATUS = (
        ('PR', "Presente"),
        ('FA', "Falta"),
        ('FV', "Falta por Viagem"),
        ('FT', "Falta por Trabalho"),
        ('FL', "Falta por Licença"),
        ('FS', "Falta por Saúde"),
        ('NA', "Não se Aplica"),
        ('NI', "Não Informado")
    )

    funcao          = models.ForeignKey(Funcao, null = False, blank = False)
    voluntario      = models.ForeignKey(Voluntario, null = False, blank = False)
    status          = models.CharField(max_length = 2, choices = STATUS, null=True, blank=True)
    data            = models.DateField(null = False, blank = False)
    hora_inicio     = models.TimeField(null=True, blank=True)
    hora_final      = models.TimeField(null=True, blank=True)

    def __unicode__(self):
        return "%s: %s - %s (%s - %s) - %s" % (self.funcao.descricao, self.voluntario.paciente.nome, self. data, self.hora_inicio, self.hora_final, self.status)

# Dúvida.
# Mantemos no model essa classe auxiliar ou criamos um relacionamento M-N diretamente em python?
class FuncaoVoluntario(models.Model):
    funcao          = models.ForeignKey("Funcao")
    voluntario      = models.ForeignKey("Voluntario")

    def __unicode__(self):
        return "%s : %s" % (self.funcao.descricao, self.voluntario.paciente.nome)

class AgendaTrabalho(models.Model):
    voluntario      = models.ForeignKey(Voluntario, null = False, blank = False)
    data            = models.DateField(null = False, blank = False)
    hora_chegada    = models.TimeField(null = True, blank = True)
    hora_saida      = models.TimeField(null = True, blank = True)

    def __unicode__(self):
        return "%s - data: %s" % (self.voluntario.paciente.nome, self.data)

src/templates/ajax-consultar-paciente.html
<style type="text/css">
@import url("/static/css/quinta.css");
</style>

<div class="paciente_consulta">
<table id="borda_fancybox">
<tr>
<td>
<table id="ajax_titulo">
<tr>
<td><img src="/static/img/icon_info.png" width="25" height="25" /> </td>
<td><b>&nbsp;&nbsp;INFORMAÇÕES DO PACIENTE</b> </td>
</tr>
<tr>
<td></td>
<td><b>&nbsp;&nbsp;{{paciente.nome}}</b></td>
</tr>
</table>

<table id="tabela_info_paciente">
    <tr>
        <td>Prioridade:</td>
        <td>{{paciente.prioridade}}</td>
    </tr>
    <tr>
        <td>Tratamento:</td>
        <td>{% for tratamento in tratamentos %}
                {{tratamento.descricao_basica}} &nbsp;
            {% endfor %}
        </td>
    <tr>
        <td>E-mail:</td>
        <td>{{paciente.email}}</td>
    </tr>
    <tr>
        <td>Telefones:</td>
        <td>{{paciente.telefones}}</td>
    </tr>
    <tr>
        <td>Data de Nascimento:</td>
        <td>{{paciente.data_nascimento}}</td>
    </tr>
    <tr>
        <td>Local de Nascimento:</td>
        <td> {{paciente.local_nascimento}}</td>
    </tr>
    <tr>
        <td>Hora de Nascimento:</td>
        <td>{{paciente.hora_nascimento}}</td>
    </tr>
    <tr>
        <td>Endereço:</td>
        <td>{{paciente.endereco}}</td>
    </tr>
    <tr>
        <td>Bairro:</td>
        <td>{{paciente.bairro}}</td>
    </tr>
    <tr>
        <td>Cidade:</td>
        <td>{{paciente.cidade}}</td>
    </tr>
    <tr>
        <td>Estado:</td>
        <td>{{paciente.estado}}</td>
    </tr>
    <tr>
        <td>CEP:</td>
        <td>{{paciente.cep}}</td>
    </tr>
    <tr>
        <td>País:</td>
        <td>{{paciente.pais}}</td>
    </tr>
    <tr>
        <td>Profissão:</td>
        <td>{{paciente.profissao}}</td>
    </tr>
    <tr>
        <td>Estado Civil:</td>
        <td>{{paciente.estado_civil}}</td>
    </tr>
    <tr>
        <td>Sexo:</td>
        <td>{{paciente.sexo}}</td>
    </tr>
    <tr>
        <td>Frequência:</td>
        <td>{{paciente.frequencia}}</td>
    </tr>
    <tr>
        <td>Observação:</td>
        <td>{{paciente.observacao}}</td>
    </tr>
    <tr>
        <td>Tem Ficha:</td>
        <td>{{paciente.tem_ficha}}</td>
    </tr>
    <tr>
        <td>Detalhes:</td>
        <td>{{paciente.detalhe_ficha}}</td>
    </tr>
</table>
<table id=tabela_links_info_paciente>
    <tr>
        <td> <a href="/paciente/{{paciente.id}}" title="Atualizar dados do paciente">
            <img src="/static/img/edit.png"  width="25" height="25"/></a>  
        </td>
        <td> <a href="/atendimento/consultar/{{paciente.id}}" title="Consultar atendimentos">
            <img src="/static/img/list.gif" width="25" height="25"/></a>  
        </td>
        <td>
            <a href="/atendimento/incluir-notificacao/{{paciente.id}}" title="Incluir notificação">
            <img alt="" width="25" height="25" src="/static/img/notification.gif" />
            </a>
        </td>
        <td>
            <a href="/atendimento/realizar-agendamento/{{paciente.id}}" title="Realizar agendamento">
            <img alt="" width="25" height="25" src="/static/img/calendar.png" />
            </a>
        </td>
        {% if voluntario %}
        <td> <a href="/voluntario/{{voluntario.id}}" title="Atualizar dados do voluntário">
            <img src="/static/img/worker-icon.gif" width="25" height="25" /></a>
        </td>
        {% endif %}
    </tr>
</table>
</td>
</tr>
</table>

</div>

src/templates/ajax-dialog-detalhe-paciente.html
<div id="detalhe-paciente">
	<div id="nome-sala">
		<h1>{{nome}}</h1>
		<p>{{sala}}</p>
	</div>
	<div id="redirecionar">
		<p>Redirecionar: 
			<select>
			{% for tratamento in tratamentos %}
				<option value="{{tratamento.id}})">{{tratamento.display}}</option>
			{% endfor %}
			</select>
		</p>
	</div>
	<div id="obs-prioritario">
		<p>Observação</p>
		<textarea id="observacao"> </textarea>
		<br />
		<input type="checkbox" id="check-prioritario"> É prioritário (ou acompanha uma pessoa prioritária)</input>
	</div>
	<div id="confirmar-chegada">
		<input id="button-confirmar" type="button" value="Confirmar Chegada" />
	</div>
</div>

src/templates/cadastro-rapido-paciente-resultado.html
<style type="text/css">
@import url("/static/css/quinta.css");
</style>

<!--
Ainda não entendi por que o título da página está vindo da página anterior...
CHECKIN RÁPIDO.
De qualquer maneira, está funcionando.
-->

<div id="div-cadastro-paciente">
{% if paciente %}
<table id="ajax_titulo">
    <tr>
        <td>{{paciente.nome}}</td>
    </tr>
</table>
{% endif %}
{% for dic in lista_dics %}
    {% if dic.sucesso %}
    <table class="ajax_resultado_checkin_rapido">
        <tr>
        <td> <img src="/static/img/sucesso.png"/> </td>
        <td> {{dic.mensagem}} </td> 
        </tr>
    </table>
    {% if dic.senha %}
        <div align="center">
        <table class=ajax_tabela_senha>
            <tr>
            <td> Senha </td> 
            </tr>
            <tr class="ajax_senha">
            <td> {{dic.senha}} </td> 
            </tr>
        </table>
        </div>
    {% endif %}        
    {% endif %}        
    {% if not dic.sucesso %}
    <table class='ajax_resultado_checkin_rapido'>
        <tr>
        <td> <img src="/static/img/falha.png"/> </td>
        <td> <font color='red'>{{dic.mensagem}} </font></td> 
        </tr>
    </table>
    {% endif %}
{% endfor %}

</div>

src/templates/checkin-detalhado-paciente.html
<div id="div-checkin-detalhado">
	<form method="post" id="form-checkin-detalhado">
		<div id="div-dados-paciente">
			<h3 id="nome">{{paciente.nome}}</h3>
			<font>{{paciente.sala}} [Qtd de tratamentos]</font>
			<p id="prioridade">{{paciente.prioridade}}</p><!-- mostrar caso prioridade -->
			<label for="senha">Senha:</senha>
			<input type="password" id="senha" name="senha" />
		</div><!-- end dados paciente -->
		<div id="div-redirecinar">
			<p>Redirecionar:
				<select>
				{% for tratamento in tratamentos %}
					<option value="{{tratamento.id}})">{{tratamento.display}}</option>
				{% endfor %}	
				</select>
			</p>
		</div><!-- end redirecinar -->
		<input type="submit" value="OK" id="btn-ok"/>
		<input type="button" value="Cancela" id="btn-cancela"/>
	</form>
</div>

src/templates/consulta_ponto.html
{% extends "base.html"%}
{% block content %}

<form name="form" method="POST" action="/voluntario/consulta-ponto/" >

<table>
       Data : {{ form.data }}
        <input type="submit" value="Pesquisar"/>
</table>
<br>

<table id="tabela-padrao">
    
	{% for voluntario in retorno %}
        {% if forloop.first %}

	      <tr>	
			<th width="40" align="center"> P/F </th>	
		    <th> Nome </th>
		    <th> Tipo </th>
		    <th> Hora Chegada </th>
		    <th> Hora Saída </th>
	      </tr>
	      
        {% endif %}
		
		  <tr>
			{% if voluntario.presente == 'P' %}
                <td align="center"> <img src="/static/img/confirma_atendimento.png" width="20" height="20" /> </td>
            {% else %} {% if voluntario.presente == 'F' %}
			    <td align="center"> <img src="/static/img/nao_confirma_atendimento.png" width="20" height="20" /> </td>
            {% endif %}
			{% endif %}
			
			<td> {{voluntario.nome}} </td>
			<td> {{voluntario.tipo}} </td>
			<td> {{voluntario.hora_chegada}} </td>
			<td> {{voluntario.hora_saida}} </td>
		  </tr>
	{% endfor %}
</table>

</form>
{% endblock %}

src/templates/crud-notificacao.html
{% extends "base.html"%}
{% block content %}
<style type="text/css">
@import url("/static/css/quinta.css");
</style>

<div class="nova_notificacao">
<form method="POST" id="form_nova_notificacao">
    <table id="cadastros_basicos_sub">
        <tr>
            <td></td>
            <td>{{form_notificacao.paciente.as_hidden}} {{paciente.nome}}</td>
        </tr>
    </table>
    <br>
    <table id="cadastros_basicos">
        <tr>
        <td> Descrição: </td>
        <td> {{form_notificacao.descricao}} </td>
        </tr>
    </table>
    <table id="cadastros_basicos">
        <tr>
        <td colspan=4> Tela Impressão: {{form_notificacao.impressao}} &nbsp; &nbsp; &nbsp; 
            Tela Checkin: {{form_notificacao.tela_checkin}} </td>
        </tr>
    </table>
    <table id="cadastros_basicos">
        <tr>
        <td> Fixo: {{form_notificacao.fixo}} </td>
        <td> Data Validade: {{form_notificacao.data_validade}} </td>
        </tr>
        <tr>
        <td> Prazo: {{form_notificacao.prazo_num}} {{form_notificacao.prazo_unidade}}</td>
        <td> Qtd. Atendimentos: {{form_notificacao.qtd_atendimentos}} </td>
        </tr>
    </table>
    <table id="cadastros_basicos">
        <tr>
        <td> Ativo: </td>
        <td> {{form_notificacao.ativo}} </td>
        </tr>
    </table>
    
    <br>
    <input type="submit" value="Confirmar"/>
</form>
</div>
{% endblock %}

src/templates/listagem-agendamentos.html
{% extends "base.html"%}
{% block content %}
<body OnLoad="document.form_listagem.paciente.focus();">
<form name="form_listagem" method="POST" action="/atendimento/listagem-agendamentos/" >

<table>
    <tr>
    <td>Paciente: </td>
    <td>{{ form_listagem.paciente }}</td>
    </tr>
    <tr>
    <td>Data agendamento: </td>
    <td>{{ form_listagem.data_prevista }}</td>
    </tr>
    <tr>
    <td>Sem data de agendamento: </td>
    <td>{{ form_listagem.sem_data }}</td>
    </tr>
    <tr>
    <td> Tratamento:</td>
    <td>{{ form_listagem.tratamento_agendado }}</td>
    </tr>
    <tr>
    <td>Data de marcação:</td>
    <td>{{ form_listagem.data_marcacao }}</td>
    </tr>
    <tr>
    <td>Tratamento de origem:</td>
    <td>{{ form_listagem.tratamento_marcacao }}</td>
    </tr>
    <tr>
    <td>Status:</td>
    <td>{{ form_listagem.status }}</td>
    </tr>
</table>
<br>
<input type="submit" value="Pesquisar"/>


<table id="tabela-padrao">
    
	{% for agendamento in agendamentos %}
        {% if forloop.first %}

	      <tr>	
			<th align="center"> Status </th>
			<th> Tratamento </th>
			<th> Data agendamento </th>
			<th> Paciente </th>
			<th> Tratamento de origem </th>
			<th> Data de marcação </th>
			<th> Atualizar </th>
			
	      </tr>
            <tbody id="tabela-fechamento">
        {% endif %}
		
		  <tr>
			{% if agendamento.status %}
    			<td> {{agendamento.get_status_display}} </td>
            {% else %} 
    			<td> - </td>
            {% endif %}

			<td> {{agendamento.agenda_tratamento.tratamento.descricao_basica}} </td>

			{% if agendamento.agenda_tratamento.data %}
    			<td> {{agendamento.agenda_tratamento.data}} </td>
            {% else %} 
    			<td> Sem data </td>
            {% endif %}

			<td> {{agendamento.paciente.nome}} </td>

			{% if agendamento.atendimento_origem %}
    			<td> {{agendamento.atendimento_origem.instancia_tratamento.tratamento.descricao_basica}} </td>
            {% else %} 
    			<td> Não informado. </td>
            {% endif %}

			{% if agendamento.data_criacao %}
                <td> {{agendamento.data_criacao}} </td>
            {% else %} 
    			<td> Não informada. </td>
            {% endif %}
			<td align="center">
                <a href="/atendimento/atualizar-agendamento/{{agendamento.id}}">
                <img alt="" width="20" height="20" src="/static/img/update.png" />
                </a>
            </td>


		  </tr>
	{% endfor %}
	</tbody>
</table>
</div>

</form>
{% endblock %}

src/templates/listagem-diaria-geral-fechamento.html
{% extends "base.html"%}
{% block content %}
<body OnLoad="document.form_listagem_fechamento.paciente.focus();">
<form name="form_listagem_fechamento" method="POST" action="/atendimento/listagem-geral-fechamento/" >

<table>
    <tr>
    <td>Paciente: </td>
    <td>{{ form_listagem_fechamento.paciente }}</td>
    </tr>
    <tr>
    <td>Data: </td>
    <td>{{ form_listagem_fechamento.data }}</td>
    </tr>
    <tr>
    <td>
    Tratamento:</td>
    <td>{{ form_listagem_fechamento.tratamento }}</td>
    </tr>
</table>
<br>
<input type="submit" value="Pesquisar"/>


<table id="tabela-padrao">
    
	{% for atendimento in retorno %}
        {% if forloop.first %}

	      <tr>	
			<th width="30" align="center"> Senha </th>	
			<th width="40" align="center"> Conf. </th>	
		    <th> Hora cheg. </th>
		    <th width="80" >Sala </th>
		    <th width="180"> Nome </th>
		    <th> Info </th>
		    <th> Observação </th>
		    <th> Atualizar </th>
	      </tr>
            <tbody id="tabela-fechamento">
	      
        {% endif %}
		
		  <tr>
			<td align="center"> {{atendimento.senha}} </td>
			
			{% if atendimento.status == 'A' %}
                <td align="center"> <img src="/static/img/confirma_atendimento.png" width="16" height="16"/> </td>
            {% else %} {% if atendimento.status == 'C' %}
			    <font color=red>
			    <td align="center"> <img src="/static/img/nao_confirma_atendimento.png" width="16" height="16"/> </td>
                </font>
            {% endif %}
			{% endif %}
			
			<td align="center"> {{atendimento.hora}} </td>
			<td> {{atendimento.sala}} </td>
			<td> {{atendimento.nome}} </td>
			<td> {{atendimento.info}} </td>
			<td> {{atendimento.observacao}} </td>
			<td align="center">
                <a href="#" class="alterar" id="{{atendimento.id}}">
                <img alt="" width="20" height="20" src="/static/img/update.png" />
                </a>
            </td>
		  </tr>
	{% endfor %}
	</tbody>
</table>
</div>

</form>
{% endblock %}

src/templates/listar-pessoas.html
{% extends "index.html" %}

{% block conteudo %}
<div class="lista-pessoas"> 
    <table>
        <thead>
            <th>Nome</th>
            <th>Sala</th>
            <th>Atendimentos</th>
            <th>Hoje</th>
        </thead>
        <tbody>
        {% for paciente in pacientes %}
            <tr>
                <td>{{paciente.nome}}</td>
                <td>{{paciente.salas}}</td>
                <td>{{paciente.atendimentos}}</td>
        {% endfor %}
        </tbody>
    <table>
</div>
{% endblock %}

src/templates/registra_ponto.html
{% extends "base.html" %}

{% block content %}
<style type="text/css">
label {
    display:none;
}
</style>

<SCRIPT LANGUAGE="JavaScript">
<!--
<!-- Begin
checked = false
function checkAll(field)
{
	 if (checked == false)
        checked = true
    else
        checked = false
          
    for (var i = 0; i < field.elements.length; i++)
        if(field.elements[i].type == 'checkbox' && field.elements[i].name != 'CheckAll')
        	field.elements[i].checked = checked ;
}

//  End -->
</script>

<form name='lista_voluntarios' action="/voluntario/registra-ponto/" method="POST">
    
    <div class="filtro">

        <table>
            <tr>
            <td>Data: </td>
            <td>&nbsp&nbsp{{ filtro_form.data }}</td>
            </tr>
            <tr>
            <td>Dia de estudo: </td>
            <td>&nbsp&nbsp{{ filtro_form.dia_estudo }}</td>
            </tr>
        </table>
        <br>
        <input type="submit" name="pesquisar" value="Pesquisar"/>
        <br>
    </div>
    <br>
    <br>

<!-- {% if voluntarios.forms %} 
    <input type="checkbox" name="CheckAll" value="CheckAll" onClick="checkAll(document.lista_voluntarios)"> Selecionar todos
{% endif %}
-->
<table>
{{voluntarios.management_form}}
{% for voluntario in voluntarios.forms %}
    {% if forloop.first %}
    <tr>
    {% for coluna in voluntario %}
        {% if coluna.label == 'Id' %}
        <th> &nbsp; </th>
        {% else %}
        <th>{{coluna.label}}</th>
        {% endif %}
    {% endfor %}
    </tr>
    {% endif %}
    <tr>
    {% for coluna in voluntario %}
        <td>
        {{coluna}}
        </td>
    {% endfor %}
    </tr>
{% endfor %}
</table>
{% if voluntarios.forms %}
    <br>    
    <input type="submit" name="salvar" value="Salvar Dados" />
{% endif %}
</form>



{% endblock %}

src/templates/relatorio-atendimentos-dia.html
{% extends "base.html"%}
{% block content %}

<form name="form" method="POST" action="/atendimento/relatorio-atendimentos-dia/" >

<table>
       Data : {{ form.data }}
        <input type="submit" value="Pesquisar"/>
</table>
<br>

<table id="tabela-padrao">
    
	{% for dado in retorno %}
        {% if forloop.first %}

	      <tr>	
			<th align="center"> Tratamento </th>	
			<th align="center"> Confirmados </th>	
			<th align="center"> Não Confirmados </th>	
			<th align="center"> Total </th>	
	      </tr>
	      
        {% endif %}
		
		  <tr>
			<td align="center"> {{dado.tratamento}} </td>
			<td align="center"> {{dado.numero_conf}} </td>
			<td align="center"> {{dado.numero_nconf}} </td>
			<td align="center"> {{dado.numero_total}} </td>
		  </tr>
	{% endfor %}
</table>

</form>






{% endblock %}

src/templates/relatorio-voluntarios.html
{% extends "base.html"%}
{% block content %}

<form name="form" method="POST" action="/voluntario/relatorio-voluntarios/" >

<table>
    <tr>
    <td>Tipo: </td>
    <td>&nbsp&nbsp{{ form.tipo }}</td>
    </tr>
    <tr>
    <td>Ativo: </td>
    <td>&nbsp&nbsp{{ form.ativo }}</td>
    </tr>
    <tr>
    <td>Dia de estudo:</td>
    <td>&nbsp&nbsp{{ form.dia_estudo }}</td>
    </tr>
</table>
<br>
<input type="submit" value="Pesquisar"/>
<br>
<table id="tabela-padrao">
    
	{% for voluntario in voluntarios %}
        {% if forloop.first %}

	      <tr>	
			<th width="40" align="center"> Ativo </th>	
		    <th width="260"> Nome </th>
		    <th> Tipo </th>
		    <th> Dia de Estudo </th>
		    <th> Telefone </th>
		    <th> E-mail </th>
		    <th> Observação </th>
	      </tr>
	      
        {% endif %}
		
		  <tr>
			{% if voluntario.ativo %}
                <td align="center" width="40"> <img src="/static/img/confirma_atendimento.png" width="20" height="20" /> </td>
            {% else %}
			    <td align="center" width="40"> <img src="/static/img/nao_confirma_atendimento.png" width="20" height="20" /> </td>
            {% endif %}
            <td width="260"> <a href="/voluntario/{{voluntario.id}}"> {{voluntario.paciente.nome}} </a> </td>
			<td> {{voluntario.tipo}} </td>
			{% if voluntario.dia_estudo %}
                <td> {{voluntario.get_dia_estudo_display}} </td>
            {% else %}
                <td> - </td>
            {% endif %}
			<td> {{voluntario.paciente.telefones}} </td>
			<td> {{voluntario.paciente.email}} </td>
			<td> {{voluntario.observacao}} </td>
		  </tr>
	{% endfor %}
</table>

</form>
{% endblock %}